-- Activities: 58 total across 6 timelines.
-- Columns: id, timeline_id, title, description, color, icon,
--          start_at, end_at, status_id,
--          parent_activity_id (NULL or sibling ID for sub-tasks),
--          percent_complete (0-100),
--          created_by, created_at, updated_at

-- ── Q1 Workload (20 activities, Workload statuses) ───────────────────────────
-- Parent-child pairs:
--   a-q1-02 (battlecard refresh) → a-q1-01 (competitive landscape)
--   a-q1-14 (AR/PR coordination) → a-q1-06 (launch checklist)
--   a-q1-17 (demo env setup)     → a-q1-06 (launch checklist)

INSERT INTO activities (id, timeline_id, title, description, color, icon, start_at, end_at, status_id, parent_activity_id, percent_complete, created_by, created_at, updated_at) VALUES
  ('a-q1-01', 'tl-pm-q1', 'Competitive landscape analysis',      'Deep-dive on top 5 competitors — positioning, pricing, recent launches.', '#3B82F6', 'search',         datetime('now', '-28 days'), datetime('now', '-18 days'), 's-q1-done',       NULL,       100, 'u-brian-rieb',  datetime('now', '-28 days'), datetime('now', '-18 days')),
  ('a-q1-02', 'tl-pm-q1', 'Competitive battlecard refresh',      'Update sales battlecards with latest competitive intel.',                  '#06B6D4', 'shield',         datetime('now', '-20 days'), datetime('now', '-12 days'), 's-q1-done',       'a-q1-01',  100, 'u-brian-rieb',  datetime('now', '-20 days'), datetime('now', '-12 days')),
  ('a-q1-03', 'tl-pm-q1', 'Q1 messaging framework',              'Core positioning and messaging for Q1 product launches.',                  '#8B5CF6', 'file-text',      datetime('now', '-25 days'), datetime('now', '-10 days'), 's-q1-done',       NULL,       100, 'u-lindsay-k',   datetime('now', '-25 days'), datetime('now', '-10 days')),
  ('a-q1-04', 'tl-pm-q1', 'Analyst briefing prep — Gartner',     'Slide deck and talking points for Gartner analyst meeting.',               '#F97316', 'briefcase',      datetime('now', '-15 days'), datetime('now', '-8 days'),  's-q1-done',       NULL,       100, 'u-erik-b',      datetime('now', '-15 days'), datetime('now', '-8 days')),
  ('a-q1-05', 'tl-pm-q1', 'Analyst briefing prep — Forrester',   'Deck and prep for Forrester wave discussion.',                             '#F97316', 'briefcase',      datetime('now', '-12 days'), datetime('now', '-5 days'),  's-q1-done',       NULL,       100, 'u-erik-b',      datetime('now', '-12 days'), datetime('now', '-5 days')),
  ('a-q1-06', 'tl-pm-q1', 'Product launch checklist — v4.2',     'End-to-end launch readiness: docs, blog, enablement, PR.',                 '#22C55E', 'check-circle',   datetime('now', '-20 days'), datetime('now', '-3 days'),  's-q1-done',       NULL,       100, 'u-brian-rieb',  datetime('now', '-20 days'), datetime('now', '-3 days')),
  ('a-q1-07', 'tl-pm-q1', 'Win/loss interview synthesis',        'Summarize Q4 win/loss interviews into themes and recommendations.',         '#EC4899', 'message-circle', datetime('now', '-18 days'), datetime('now', '-7 days'),  's-q1-done',       NULL,       100, 'u-michelle-t',  datetime('now', '-18 days'), datetime('now', '-7 days')),
  ('a-q1-08', 'tl-pm-q1', 'Pricing positioning doc',             'Updated pricing rationale and competitive positioning matrix.',             '#F43F5E', 'trending-up',    datetime('now', '-10 days'), datetime('now', '+5 days'),  's-q1-inprogress', NULL,        60, 'u-brian-rieb',  datetime('now', '-10 days'), datetime('now', '-2 days')),
  ('a-q1-09', 'tl-pm-q1', 'Sales one-pager refresh',             'Refresh the 2-sided sales leave-behind for Q1 messaging.',                 '#84CC16', 'file-text',      datetime('now', '-8 days'),  datetime('now', '+3 days'),  's-q1-inprogress', NULL,        45, 'u-lindsay-k',   datetime('now', '-8 days'),  datetime('now', '-2 days')),
  ('a-q1-10', 'tl-pm-q1', 'Customer story — Acme Corp',          'Draft case study from Acme Corp expansion deal.',                          '#288C9B', 'star',           datetime('now', '-14 days'), datetime('now', '-4 days'),  's-q1-done',       NULL,       100, 'u-michelle-t',  datetime('now', '-14 days'), datetime('now', '-4 days')),
  ('a-q1-11', 'tl-pm-q1', 'Content calendar planning',           'Map out blog, social, and email content for next 6 weeks.',                '#A855F7', 'calendar',       datetime('now', '-5 days'),  datetime('now', '+7 days'),  's-q1-inprogress', NULL,        50, 'u-lindsay-k',   datetime('now', '-5 days'),  datetime('now', '-1 days')),
  ('a-q1-12', 'tl-pm-q1', 'Webinar script — platform overview',  'Script and slide deck for monthly product webinar.',                       '#6366F1', 'edit',           datetime('now', '-3 days'),  datetime('now', '+10 days'), 's-q1-planning',   NULL,         0, 'u-erik-b',      datetime('now', '-3 days'),  datetime('now', '-1 days')),
  ('a-q1-13', 'tl-pm-q1', 'Partner co-marketing brief',          'Joint value prop and co-marketing plan with PartnerCo.',                   '#F59E0B', 'share',          datetime('now', '-7 days'),  datetime('now', '+4 days'),  's-q1-inprogress', NULL,        35, 'u-brian-rieb',  datetime('now', '-7 days'),  datetime('now', '-1 days')),
  ('a-q1-14', 'tl-pm-q1', 'AR/PR coordination — Q1 launch',     'Coordinate PR release and analyst outreach for v4.2 launch.',              '#EF4444', 'globe',          datetime('now', '-6 days'),  datetime('now', '+5 days'),  's-q1-inprogress', 'a-q1-06',   40, 'u-erik-b',      datetime('now', '-6 days'),  datetime('now', '-1 days')),
  ('a-q1-15', 'tl-pm-q1', 'Persona refresh workshop',            'Internal workshop to validate and update buyer personas.',                 '#78716C', 'users',          datetime('now', '+2 days'),  datetime('now', '+5 days'),  's-q1-planning',   NULL,         0, 'u-michelle-t',  datetime('now', '-2 days'),  datetime('now', '-1 days')),
  ('a-q1-16', 'tl-pm-q1', 'ROI calculator update',               'Refresh the interactive ROI calculator with new benchmark data.',          '#06B6D4', 'pie-chart',      datetime('now', '+5 days'),  datetime('now', '+18 days'), 's-q1-planning',   NULL,         0, 'u-brian-rieb',  datetime('now', '-1 days'),  datetime('now', '-1 days')),
  ('a-q1-17', 'tl-pm-q1', 'Demo environment setup',              'Provision and configure demo environment for Q1 launches.',                '#288C9B', 'server',         datetime('now', '-4 days'),  datetime('now', '+3 days'),  's-q1-blockers',   'a-q1-06',   30, 'u-erik-b',      datetime('now', '-4 days'),  datetime('now', '-1 days')),
  ('a-q1-18', 'tl-pm-q1', 'Competitive teardown — NewCo launch', 'Rapid response analysis of NewCo product announcement.',                  '#EF4444', 'alert-circle',   datetime('now', '+7 days'),  datetime('now', '+14 days'), 's-q1-planning',   NULL,         0, 'u-brian-rieb',  datetime('now', '-1 days'),  datetime('now', '-1 days')),
  ('a-q1-19', 'tl-pm-q1', 'Sales enablement newsletter — March', 'Monthly enablement digest: new assets, competitive updates, wins.',        '#22C55E', 'mail',           datetime('now', '+10 days'), datetime('now', '+14 days'), 's-q1-planning',   NULL,         0, 'u-lindsay-k',   datetime('now', '-1 days'),  datetime('now', '-1 days')),
  ('a-q1-20', 'tl-pm-q1', 'Quarterly business review deck',      'PMM section of the QBR deck: pipeline impact, content metrics.',           '#F97316', 'bar-chart',      datetime('now', '+14 days'), datetime('now', '+21 days'), 's-q1-planning',   NULL,         0, 'u-brian-rieb',  datetime('now', '-1 days'),  datetime('now', '-1 days'));

-- ── Sales Kick Off (10 activities, Default statuses) ─────────────────────────
-- Parent-child pair:
--   a-sko-07 (sales training — pricing) → a-sko-05 (objection handling playbook)

INSERT INTO activities (id, timeline_id, title, description, color, icon, start_at, end_at, status_id, parent_activity_id, percent_complete, created_by, created_at, updated_at) VALUES
  ('a-sko-01', 'tl-pm-sko', 'SKO keynote deck',                    'Main stage presentation — product vision and roadmap.',                  '#3B82F6', 'star',           datetime('now', '+2 days'),  datetime('now', '+14 days'), 's-sko-inprogress', NULL,        55, 'u-erik-b',     datetime('now', '-10 days'), datetime('now', '-1 days')),
  ('a-sko-02', 'tl-pm-sko', 'Competitive battle card workshop',    'Interactive session: how to use battlecards in live deals.',             '#EF4444', 'shield',         datetime('now', '+7 days'),  datetime('now', '+12 days'), 's-sko-planning',   NULL,         0, 'u-brian-rieb', datetime('now', '-10 days'), datetime('now', '-1 days')),
  ('a-sko-03', 'tl-pm-sko', 'Demo script — enterprise tier',       'Step-by-step demo flow for enterprise prospects.',                       '#22C55E', 'code',           datetime('now', '+3 days'),  datetime('now', '+10 days'), 's-sko-inprogress', NULL,        40, 'u-erik-b',     datetime('now', '-8 days'),  datetime('now', '-1 days')),
  ('a-sko-04', 'tl-pm-sko', 'New rep onboarding kit',              'Welcome pack: product overview, personas, competitive cheat sheet.',     '#F97316', 'package',        datetime('now', '+5 days'),  datetime('now', '+15 days'), 's-sko-planning',   NULL,         0, 'u-lindsay-k',  datetime('now', '-7 days'),  datetime('now', '-1 days')),
  ('a-sko-05', 'tl-pm-sko', 'Objection handling playbook',         'Top 15 objections with response frameworks and proof points.',           '#8B5CF6', 'message-circle', datetime('now', '+8 days'),  datetime('now', '+18 days'), 's-sko-planning',   NULL,         0, 'u-brian-rieb', datetime('now', '-6 days'),  datetime('now', '-1 days')),
  ('a-sko-06', 'tl-pm-sko', 'Customer story video — GlobalTech',   'Film and edit 3-minute customer testimonial video.',                     '#EC4899', 'eye',            datetime('now', '+1 days'),  datetime('now', '+20 days'), 's-sko-inprogress', NULL,        70, 'u-michelle-t', datetime('now', '-12 days'), datetime('now', '-1 days')),
  ('a-sko-07', 'tl-pm-sko', 'Sales training session — pricing',    'Live training: positioning premium tier and handling price objections.', '#F59E0B', 'trending-up',    datetime('now', '+14 days'), datetime('now', '+16 days'), 's-sko-planning',   'a-sko-05',   0, 'u-brian-rieb', datetime('now', '-5 days'),  datetime('now', '-1 days')),
  ('a-sko-08', 'tl-pm-sko', 'SKO swag and logistics',              'Coordinate branded materials, venue AV, and printed collateral.',        '#64748B', 'package',        datetime('now'),             datetime('now', '+25 days'), 's-sko-inprogress', NULL,        25, 'u-lindsay-k',  datetime('now', '-14 days'), datetime('now', '-1 days')),
  ('a-sko-09', 'tl-pm-sko', 'Breakout session — vertical selling', 'Prep for healthcare and finserv vertical breakout sessions.',            '#06B6D4', 'layers',         datetime('now', '+10 days'), datetime('now', '+18 days'), 's-sko-planning',   NULL,         0, 'u-erik-b',     datetime('now', '-4 days'),  datetime('now', '-1 days')),
  ('a-sko-10', 'tl-pm-sko', 'Post-SKO follow-up plan',             'Email sequences and resource hub for post-event reinforcement.',         '#84CC16', 'mail',           datetime('now', '+20 days'), datetime('now', '+30 days'), 's-sko-planning',   NULL,         0, 'u-michelle-t', datetime('now', '-3 days'),  datetime('now', '-1 days'));

-- ── Q2 Workload (5 activities, archived, Workload statuses) ──────────────────

INSERT INTO activities (id, timeline_id, title, description, color, icon, start_at, end_at, status_id, parent_activity_id, percent_complete, created_by, created_at, updated_at) VALUES
  ('a-q2-01', 'tl-pm-q2', 'Q2 product launch plan',           'High-level launch timeline and DRI assignments for Q2 releases.',     '#3B82F6', 'calendar',     datetime('now', '-175 days'), datetime('now', '-140 days'), 's-q2-done',     NULL, 100, 'u-brian-rieb', datetime('now', '-178 days'), datetime('now', '-140 days')),
  ('a-q2-02', 'tl-pm-q2', 'Analyst day preparation',           'Materials and dry-run for annual analyst day event.',                 '#F97316', 'briefcase',    datetime('now', '-160 days'), datetime('now', '-130 days'), 's-q2-done',     NULL, 100, 'u-erik-b',     datetime('now', '-165 days'), datetime('now', '-130 days')),
  ('a-q2-03', 'tl-pm-q2', 'Mid-year messaging audit',          'Review all external messaging for consistency with Q2 positioning.', '#EC4899', 'eye',          datetime('now', '-145 days'), datetime('now', '-115 days'), 's-q2-done',     NULL, 100, 'u-lindsay-k',  datetime('now', '-150 days'), datetime('now', '-115 days')),
  ('a-q2-04', 'tl-pm-q2', 'Competitive intel digest — June',   'Monthly competitive summary for sales and leadership.',              '#EF4444', 'alert-circle', datetime('now', '-120 days'), datetime('now', '-100 days'), 's-q2-done',     NULL, 100, 'u-brian-rieb', datetime('now', '-125 days'), datetime('now', '-100 days')),
  ('a-q2-05', 'tl-pm-q2', 'Customer advisory board planning',  'Agenda and invite list for H2 customer advisory board session.',     '#22C55E', 'users',        datetime('now', '-110 days'), datetime('now', '-92 days'),  's-q2-deferred', NULL,   0, 'u-michelle-t', datetime('now', '-115 days'), datetime('now', '-92 days'));

-- ── Right to Win Initiative (4 activities, Default statuses) ─────────────────

INSERT INTO activities (id, timeline_id, title, description, color, icon, start_at, end_at, status_id, parent_activity_id, percent_complete, created_by, created_at, updated_at) VALUES
  ('a-rtw-01', 'tl-pb-rtw', 'Market sizing research',         'TAM/SAM/SOM analysis for the target segment.',                       '#3B82F6', 'pie-chart',      datetime('now', '-118 days'), datetime('now', '-100 days'), 's-rtw-done', NULL, 100, 'u-dan-s',     datetime('now', '-118 days'), datetime('now', '-100 days')),
  ('a-rtw-02', 'tl-pb-rtw', 'Customer interview round',       'Interview 8 target-segment customers on needs and pain points.',     '#22C55E', 'message-circle', datetime('now', '-105 days'), datetime('now', '-85 days'),  's-rtw-done', NULL, 100, 'u-kristen-k', datetime('now', '-105 days'), datetime('now', '-85 days')),
  ('a-rtw-03', 'tl-pb-rtw', 'Right-to-win framework doc',     'Synthesize research into the right-to-win positioning framework.',   '#F97316', 'file-text',      datetime('now', '-90 days'),  datetime('now', '-70 days'),  's-rtw-done', NULL, 100, 'u-brian-rieb', datetime('now', '-90 days'),  datetime('now', '-70 days')),
  ('a-rtw-04', 'tl-pb-rtw', 'Leadership presentation',        'Present findings and recommendation to exec team.',                  '#8B5CF6', 'award',          datetime('now', '-72 days'),  datetime('now', '-62 days'),  's-rtw-done', NULL, 100, 'u-codi-k',    datetime('now', '-72 days'),  datetime('now', '-62 days'));

-- ── Displacement GTM (4 activities, Default statuses) ────────────────────────

INSERT INTO activities (id, timeline_id, title, description, color, icon, start_at, end_at, status_id, parent_activity_id, percent_complete, created_by, created_at, updated_at) VALUES
  ('a-gtm-01', 'tl-pb-gtm', 'Displacement playbook draft',    'End-to-end playbook: triggers, objections, migration path.',         '#EF4444', 'flag',        datetime('now', '-148 days'), datetime('now', '-120 days'), 's-gtm-done', NULL, 100, 'u-codi-k',           datetime('now', '-148 days'), datetime('now', '-120 days')),
  ('a-gtm-02', 'tl-pb-gtm', 'Migration ROI calculator',       'Build ROI model showing TCO advantage of switching.',               '#22C55E', 'trending-up', datetime('now', '-125 days'), datetime('now', '-95 days'),  's-gtm-done', NULL, 100, 'u-dan-s',            datetime('now', '-125 days'), datetime('now', '-95 days')),
  ('a-gtm-03', 'tl-pb-gtm', 'Sales enablement training',      'Train AEs on displacement selling motion and objection handling.',   '#F59E0B', 'users',       datetime('now', '-100 days'), datetime('now', '-75 days'),  's-gtm-done', NULL, 100, 'u-jamie-f',          datetime('now', '-100 days'), datetime('now', '-75 days')),
  ('a-gtm-04', 'tl-pb-gtm', 'Pilot program launch',           'Identify 3 pilot accounts and run displacement proof-of-concept.',  '#3B82F6', 'target',      datetime('now', '-80 days'),  datetime('now', '-62 days'),  's-gtm-done', NULL, 100, 'u-scott-fitzgerald', datetime('now', '-80 days'),  datetime('now', '-62 days'));

-- ── Web Site Rebrand (15 activities, Workload statuses) ──────────────────────
-- Parent-child pairs:
--   a-reb-08 (product pages rewrite) → a-reb-02 (design system v2)
--   a-reb-09 (blog template redesign) → a-reb-02 (design system v2)

INSERT INTO activities (id, timeline_id, title, description, color, icon, start_at, end_at, status_id, parent_activity_id, percent_complete, created_by, created_at, updated_at) VALUES
  ('a-reb-01', 'tl-mcf-rebrand', 'Brand audit and gap analysis',        'Audit current brand assets against new brand strategy.',              '#8B5CF6', 'search',       datetime('now', '-58 days'), datetime('now', '-42 days'), 's-reb-done',       NULL,       100, 'u-scott-fitzgerald', datetime('now', '-58 days'), datetime('now', '-42 days')),
  ('a-reb-02', 'tl-mcf-rebrand', 'Design system v2',                    'New component library: typography, color, spacing, elevation.',       '#3B82F6', 'grid',         datetime('now', '-50 days'), datetime('now', '-25 days'), 's-reb-done',       NULL,       100, 'u-paula-h',          datetime('now', '-50 days'), datetime('now', '-25 days')),
  ('a-reb-03', 'tl-mcf-rebrand', 'Homepage hero redesign',              'New hero section: headline, value prop, CTA, and imagery.',           '#EC4899', 'eye',          datetime('now', '-30 days'), datetime('now', '-10 days'), 's-reb-done',       NULL,       100, 'u-corey-f',          datetime('now', '-30 days'), datetime('now', '-10 days')),
  ('a-reb-04', 'tl-mcf-rebrand', 'SEO keyword audit',                   'Comprehensive keyword analysis and content gap identification.',      '#22C55E', 'search',       datetime('now', '-45 days'), datetime('now', '-20 days'), 's-reb-done',       NULL,       100, 'u-rick-s',           datetime('now', '-45 days'), datetime('now', '-20 days')),
  ('a-reb-05', 'tl-mcf-rebrand', 'Content migration plan',              'Map existing pages to new IA; identify pages to create/retire.',      '#F97316', 'list',         datetime('now', '-35 days'), datetime('now', '-15 days'), 's-reb-done',       NULL,       100, 'u-dan-b',            datetime('now', '-35 days'), datetime('now', '-15 days')),
  ('a-reb-06', 'tl-mcf-rebrand', 'Analytics tagging spec',              'Define UTM strategy, event taxonomy, and GA4 configuration.',         '#06B6D4', 'pie-chart',    datetime('now', '-20 days'), datetime('now', '-5 days'),  's-reb-done',       NULL,       100, 'u-rick-s',           datetime('now', '-20 days'), datetime('now', '-5 days')),
  ('a-reb-07', 'tl-mcf-rebrand', 'Accessibility audit',                 'WCAG 2.1 AA audit of all new page templates.',                       '#F43F5E', 'shield',       datetime('now', '-10 days'), datetime('now', '+5 days'),  's-reb-inprogress', NULL,        60, 'u-corey-f',          datetime('now', '-10 days'), datetime('now', '-2 days')),
  ('a-reb-08', 'tl-mcf-rebrand', 'Product pages rewrite',               'Rewrite all product/feature pages with new messaging.',               '#A855F7', 'file-text',    datetime('now', '-8 days'),  datetime('now', '+15 days'), 's-reb-inprogress', 'a-reb-02',  30, 'u-scott-fitzgerald', datetime('now', '-8 days'),  datetime('now', '-1 days')),
  ('a-reb-09', 'tl-mcf-rebrand', 'Blog template redesign',              'New blog index and post templates matching brand refresh.',            '#84CC16', 'edit',         datetime('now', '-5 days'),  datetime('now', '+10 days'), 's-reb-inprogress', 'a-reb-02',  45, 'u-paula-h',          datetime('now', '-5 days'),  datetime('now', '-1 days')),
  ('a-reb-10', 'tl-mcf-rebrand', 'Stakeholder review — round 1',        'First exec review of homepage, product pages, and navigation.',       '#64748B', 'users',        datetime('now', '+5 days'),  datetime('now', '+8 days'),  's-reb-planning',   NULL,         0, 'u-scott-fitzgerald', datetime('now', '-3 days'),  datetime('now', '-1 days')),
  ('a-reb-11', 'tl-mcf-rebrand', 'Photography and illustration sprint', 'Commission new brand photography and custom illustrations.',          '#F59E0B', 'eye',          datetime('now', '+3 days'),  datetime('now', '+25 days'), 's-reb-planning',   NULL,         0, 'u-paula-h',          datetime('now', '-2 days'),  datetime('now', '-1 days')),
  ('a-reb-12', 'tl-mcf-rebrand', 'Pricing page overhaul',               'Redesign pricing page with new tier structure and FAQ.',              '#EF4444', 'trending-up',  datetime('now', '+10 days'), datetime('now', '+30 days'), 's-reb-planning',   NULL,         0, 'u-dan-b',            datetime('now', '-2 days'),  datetime('now', '-1 days')),
  ('a-reb-13', 'tl-mcf-rebrand', 'Redirect map and 301 plan',           'Map all old URLs to new structure; configure redirects.',             '#78716C', 'link',         datetime('now', '+15 days'), datetime('now', '+35 days'), 's-reb-planning',   NULL,         0, 'u-rick-s',           datetime('now', '-1 days'),  datetime('now', '-1 days')),
  ('a-reb-14', 'tl-mcf-rebrand', 'Launch readiness checklist',          'Pre-launch verification: performance, SEO, analytics, redirects.',   '#288C9B', 'check-circle', datetime('now', '+30 days'), datetime('now', '+40 days'), 's-reb-planning',   NULL,         0, 'u-scott-fitzgerald', datetime('now', '-1 days'),  datetime('now', '-1 days')),
  ('a-reb-15', 'tl-mcf-rebrand', 'Post-launch monitoring plan',         'Week-1 monitoring: traffic, errors, search console, conversions.',   '#F97316', 'activity',     datetime('now', '+40 days'), datetime('now', '+50 days'), 's-reb-planning',   NULL,         0, 'u-rick-s',           datetime('now', '-1 days'),  datetime('now', '-1 days'));
