// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package api

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes bearerAuthContextKey = "bearerAuth.Scopes"
)

// Defines values for HealthResponseStatus.
const (
	Ok HealthResponseStatus = "ok"
)

// Valid indicates whether the value is a known member of the HealthResponseStatus enum.
func (e HealthResponseStatus) Valid() bool {
	switch e {
	case Ok:
		return true
	default:
		return false
	}
}

// Defines values for InviteRole.
const (
	InviteRoleAdmin  InviteRole = "admin"
	InviteRoleMember InviteRole = "member"
)

// Valid indicates whether the value is a known member of the InviteRole enum.
func (e InviteRole) Valid() bool {
	switch e {
	case InviteRoleAdmin:
		return true
	case InviteRoleMember:
		return true
	default:
		return false
	}
}

// Defines values for TeamMemberRole.
const (
	TeamMemberRoleAdmin  TeamMemberRole = "admin"
	TeamMemberRoleMember TeamMemberRole = "member"
	TeamMemberRoleOwner  TeamMemberRole = "owner"
)

// Valid indicates whether the value is a known member of the TeamMemberRole enum.
func (e TeamMemberRole) Valid() bool {
	switch e {
	case TeamMemberRoleAdmin:
		return true
	case TeamMemberRoleMember:
		return true
	case TeamMemberRoleOwner:
		return true
	default:
		return false
	}
}

// Defines values for TeamMemberWithUserRole.
const (
	TeamMemberWithUserRoleAdmin  TeamMemberWithUserRole = "admin"
	TeamMemberWithUserRoleMember TeamMemberWithUserRole = "member"
	TeamMemberWithUserRoleOwner  TeamMemberWithUserRole = "owner"
)

// Valid indicates whether the value is a known member of the TeamMemberWithUserRole enum.
func (e TeamMemberWithUserRole) Valid() bool {
	switch e {
	case TeamMemberWithUserRoleAdmin:
		return true
	case TeamMemberWithUserRoleMember:
		return true
	case TeamMemberWithUserRoleOwner:
		return true
	default:
		return false
	}
}

// Defines values for TimelineVisibility.
const (
	TimelineVisibilityPublic     TimelineVisibility = "public"
	TimelineVisibilityRestricted TimelineVisibility = "restricted"
)

// Valid indicates whether the value is a known member of the TimelineVisibility enum.
func (e TimelineVisibility) Valid() bool {
	switch e {
	case TimelineVisibilityPublic:
		return true
	case TimelineVisibilityRestricted:
		return true
	default:
		return false
	}
}

// Defines values for CreateInviteJSONBodyRole.
const (
	CreateInviteJSONBodyRoleAdmin  CreateInviteJSONBodyRole = "admin"
	CreateInviteJSONBodyRoleMember CreateInviteJSONBodyRole = "member"
)

// Valid indicates whether the value is a known member of the CreateInviteJSONBodyRole enum.
func (e CreateInviteJSONBodyRole) Valid() bool {
	switch e {
	case CreateInviteJSONBodyRoleAdmin:
		return true
	case CreateInviteJSONBodyRoleMember:
		return true
	default:
		return false
	}
}

// Defines values for CreateTimelineJSONBodyVisibility.
const (
	CreateTimelineJSONBodyVisibilityPublic     CreateTimelineJSONBodyVisibility = "public"
	CreateTimelineJSONBodyVisibilityRestricted CreateTimelineJSONBodyVisibility = "restricted"
)

// Valid indicates whether the value is a known member of the CreateTimelineJSONBodyVisibility enum.
func (e CreateTimelineJSONBodyVisibility) Valid() bool {
	switch e {
	case CreateTimelineJSONBodyVisibilityPublic:
		return true
	case CreateTimelineJSONBodyVisibilityRestricted:
		return true
	default:
		return false
	}
}

// ApiError defines model for ApiError.
type ApiError struct {
	Error struct {
		Code    string `json:"code"`
		Message string `json:"message"`
	} `json:"error"`
}

// AuthResponse defines model for AuthResponse.
type AuthResponse struct {
	AccessToken  string `json:"accessToken"`
	RefreshToken string `json:"refreshToken"`
	User         User   `json:"user"`
}

// Event defines model for Event.
type Event struct {
	AllDay          bool       `json:"allDay"`
	ArchivedAt      *time.Time `json:"archivedAt,omitempty"`
	CaldavUid       *string    `json:"caldavUid,omitempty"`
	Color           *string    `json:"color,omitempty"`
	CreatedAt       time.Time  `json:"createdAt"`
	CreatedBy       string     `json:"createdBy"`
	Description     *string    `json:"description,omitempty"`
	EndAt           time.Time  `json:"endAt"`
	GoogleEventId   *string    `json:"googleEventId,omitempty"`
	Icon            *string    `json:"icon,omitempty"`
	Id              string     `json:"id"`
	Location        *string    `json:"location,omitempty"`
	ParentEventId   *string    `json:"parentEventId,omitempty"`
	PercentComplete *int       `json:"percentComplete,omitempty"`
	Rrule           *string    `json:"rrule,omitempty"`
	StartAt         time.Time  `json:"startAt"`
	StatusId        *string    `json:"statusId,omitempty"`
	TeamId          string     `json:"teamId"`
	Title           string     `json:"title"`
	UpdatedAt       time.Time  `json:"updatedAt"`
	Url             *string    `json:"url,omitempty"`
}

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	Status HealthResponseStatus `json:"status"`
}

// HealthResponseStatus defines model for HealthResponse.Status.
type HealthResponseStatus string

// Invite defines model for Invite.
type Invite struct {
	AcceptedAt *time.Time `json:"acceptedAt,omitempty"`
	CreatedAt  time.Time  `json:"createdAt"`
	Email      string     `json:"email"`
	ExpiresAt  time.Time  `json:"expiresAt"`
	Id         string     `json:"id"`
	InvitedBy  string     `json:"invitedBy"`
	Role       InviteRole `json:"role"`
	TeamId     string     `json:"teamId"`
	Token      string     `json:"token"`
}

// InviteRole defines model for Invite.Role.
type InviteRole string

// RefreshResponse defines model for RefreshResponse.
type RefreshResponse struct {
	AccessToken string `json:"accessToken"`
}

// SavedFilter defines model for SavedFilter.
type SavedFilter struct {
	CreatedAt time.Time `json:"createdAt"`

	// Definition Opaque JSON filter spec (validated client-side).
	Definition string    `json:"definition"`
	Id         string    `json:"id"`
	Name       string    `json:"name"`
	TeamId     string    `json:"teamId"`
	UpdatedAt  time.Time `json:"updatedAt"`
	UserId     string    `json:"userId"`
}

// Team defines model for Team.
type Team struct {
	CreatedAt time.Time `json:"createdAt"`
	Id        string    `json:"id"`
	Name      string    `json:"name"`
	Slug      string    `json:"slug"`
	UpdatedAt time.Time `json:"updatedAt"`
}

// TeamMember defines model for TeamMember.
type TeamMember struct {
	Color    *string        `json:"color,omitempty"`
	JoinedAt time.Time      `json:"joinedAt"`
	Role     TeamMemberRole `json:"role"`
	TeamId   string         `json:"teamId"`
	UserId   string         `json:"userId"`
}

// TeamMemberRole defines model for TeamMember.Role.
type TeamMemberRole string

// TeamMemberWithUser defines model for TeamMemberWithUser.
type TeamMemberWithUser struct {
	AvatarUrl   *string                `json:"avatarUrl,omitempty"`
	Color       *string                `json:"color,omitempty"`
	DisplayName string                 `json:"displayName"`
	Email       openapi_types.Email    `json:"email"`
	JoinedAt    time.Time              `json:"joinedAt"`
	Role        TeamMemberWithUserRole `json:"role"`
	TeamId      string                 `json:"teamId"`
	UserId      string                 `json:"userId"`
}

// TeamMemberWithUserRole defines model for TeamMemberWithUser.Role.
type TeamMemberWithUserRole string

// Timeline defines model for Timeline.
type Timeline struct {
	ArchivedAt *time.Time         `json:"archivedAt,omitempty"`
	CreatedAt  time.Time          `json:"createdAt"`
	CreatedBy  string             `json:"createdBy"`
	EndDate    openapi_types.Date `json:"endDate"`
	IcalToken  string             `json:"icalToken"`
	Id         string             `json:"id"`
	Name       string             `json:"name"`
	ShareToken string             `json:"shareToken"`
	StartDate  openapi_types.Date `json:"startDate"`
	TeamId     string             `json:"teamId"`
	UpdatedAt  time.Time          `json:"updatedAt"`
	Visibility TimelineVisibility `json:"visibility"`
}

// TimelineVisibility defines model for Timeline.Visibility.
type TimelineVisibility string

// User defines model for User.
type User struct {
	AvatarUrl   *string             `json:"avatarUrl,omitempty"`
	CreatedAt   time.Time           `json:"createdAt"`
	DisplayName string              `json:"displayName"`
	Email       openapi_types.Email `json:"email"`
	Id          string              `json:"id"`
	UpdatedAt   time.Time           `json:"updatedAt"`
}

// EventId defines model for eventId.
type EventId = string

// SavedFilterId defines model for savedFilterId.
type SavedFilterId = string

// ShareToken defines model for shareToken.
type ShareToken = string

// TeamId defines model for teamId.
type TeamId = string

// TimelineId defines model for timelineId.
type TimelineId = string

// BadRequest defines model for BadRequest.
type BadRequest = ApiError

// Forbidden defines model for Forbidden.
type Forbidden = ApiError

// InternalError defines model for InternalError.
type InternalError = ApiError

// NotFound defines model for NotFound.
type NotFound = ApiError

// PaymentRequired defines model for PaymentRequired.
type PaymentRequired = ApiError

// Unauthorized defines model for Unauthorized.
type Unauthorized = ApiError

// bearerAuthContextKey is the context key for bearerAuth security scheme
type bearerAuthContextKey string

// LoginJSONBody defines parameters for Login.
type LoginJSONBody struct {
	Email    openapi_types.Email `json:"email"`
	Password string              `json:"password"`
}

// RefreshTokenJSONBody defines parameters for RefreshToken.
type RefreshTokenJSONBody struct {
	RefreshToken string `json:"refreshToken"`
}

// RegisterJSONBody defines parameters for Register.
type RegisterJSONBody struct {
	DisplayName string              `json:"displayName"`
	Email       openapi_types.Email `json:"email"`
	InviteToken *string             `json:"inviteToken,omitempty"`
	Password    string              `json:"password"`
}

// UpdateEventJSONBody defines parameters for UpdateEvent.
type UpdateEventJSONBody struct {
	AllDay          *bool      `json:"allDay,omitempty"`
	Color           *string    `json:"color,omitempty"`
	Description     *string    `json:"description,omitempty"`
	EndAt           *time.Time `json:"endAt,omitempty"`
	Icon            *string    `json:"icon,omitempty"`
	Location        *string    `json:"location,omitempty"`
	ParentEventId   *string    `json:"parentEventId,omitempty"`
	PercentComplete *int       `json:"percentComplete,omitempty"`
	Rrule           *string    `json:"rrule,omitempty"`
	StartAt         *time.Time `json:"startAt,omitempty"`
	StatusId        *string    `json:"statusId,omitempty"`
	Title           *string    `json:"title,omitempty"`
	Url             *string    `json:"url,omitempty"`
}

// UpdateSavedFilterJSONBody defines parameters for UpdateSavedFilter.
type UpdateSavedFilterJSONBody struct {
	Definition *string `json:"definition,omitempty"`
	Name       *string `json:"name,omitempty"`
}

// CreateTeamJSONBody defines parameters for CreateTeam.
type CreateTeamJSONBody struct {
	Name string `json:"name"`
}

// ListEventsParams defines parameters for ListEvents.
type ListEventsParams struct {
	// From Only return events where startAt >= from (RFC 3339).
	From *time.Time `form:"from,omitempty" json:"from,omitempty"`

	// To Only return events where startAt <= to (RFC 3339).
	To *time.Time `form:"to,omitempty" json:"to,omitempty"`
}

// CreateEventJSONBody defines parameters for CreateEvent.
type CreateEventJSONBody struct {
	AllDay          *bool     `json:"allDay,omitempty"`
	Color           *string   `json:"color,omitempty"`
	Description     *string   `json:"description,omitempty"`
	EndAt           time.Time `json:"endAt"`
	Icon            *string   `json:"icon,omitempty"`
	Location        *string   `json:"location,omitempty"`
	ParentEventId   *string   `json:"parentEventId,omitempty"`
	PercentComplete *int      `json:"percentComplete,omitempty"`
	Rrule           *string   `json:"rrule,omitempty"`
	StartAt         time.Time `json:"startAt"`
	StatusId        *string   `json:"statusId,omitempty"`
	Title           string    `json:"title"`
	Url             *string   `json:"url,omitempty"`
}

// CreateInviteJSONBody defines parameters for CreateInvite.
type CreateInviteJSONBody struct {
	// Email If provided, the invite is scoped to this email address.
	Email *openapi_types.Email      `json:"email,omitempty"`
	Role  *CreateInviteJSONBodyRole `json:"role,omitempty"`
}

// CreateInviteJSONBodyRole defines parameters for CreateInvite.
type CreateInviteJSONBodyRole string

// CreateSavedFilterJSONBody defines parameters for CreateSavedFilter.
type CreateSavedFilterJSONBody struct {
	// Definition Opaque JSON filter spec (validated client-side).
	Definition string `json:"definition"`
	Name       string `json:"name"`
}

// CreateTimelineJSONBody defines parameters for CreateTimeline.
type CreateTimelineJSONBody struct {
	EndDate    openapi_types.Date                `json:"endDate"`
	Name       string                            `json:"name"`
	StartDate  openapi_types.Date                `json:"startDate"`
	Visibility *CreateTimelineJSONBodyVisibility `json:"visibility,omitempty"`
}

// CreateTimelineJSONBodyVisibility defines parameters for CreateTimeline.
type CreateTimelineJSONBodyVisibility string

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody LoginJSONBody

// RefreshTokenJSONRequestBody defines body for RefreshToken for application/json ContentType.
type RefreshTokenJSONRequestBody RefreshTokenJSONBody

// RegisterJSONRequestBody defines body for Register for application/json ContentType.
type RegisterJSONRequestBody RegisterJSONBody

// UpdateEventJSONRequestBody defines body for UpdateEvent for application/json ContentType.
type UpdateEventJSONRequestBody UpdateEventJSONBody

// UpdateSavedFilterJSONRequestBody defines body for UpdateSavedFilter for application/json ContentType.
type UpdateSavedFilterJSONRequestBody UpdateSavedFilterJSONBody

// CreateTeamJSONRequestBody defines body for CreateTeam for application/json ContentType.
type CreateTeamJSONRequestBody CreateTeamJSONBody

// CreateEventJSONRequestBody defines body for CreateEvent for application/json ContentType.
type CreateEventJSONRequestBody CreateEventJSONBody

// CreateInviteJSONRequestBody defines body for CreateInvite for application/json ContentType.
type CreateInviteJSONRequestBody CreateInviteJSONBody

// CreateSavedFilterJSONRequestBody defines body for CreateSavedFilter for application/json ContentType.
type CreateSavedFilterJSONRequestBody CreateSavedFilterJSONBody

// CreateTimelineJSONRequestBody defines body for CreateTimeline for application/json ContentType.
type CreateTimelineJSONRequestBody CreateTimelineJSONBody
