/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health check */
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register a new user
         * @description The first user on a fresh install may register without an invite token
         *     (bootstrap). Every subsequent user must supply a valid invite token.
         */
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Authenticate and obtain tokens */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Exchange a refresh token for a new access token */
        post: operations["refreshToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the authenticated user's profile */
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/me/preferences": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get preferences for the authenticated user
         * @description Returns all preferences matching the given scope. Omit timeline_id
         *     (or pass an empty string) to fetch global preferences.
         */
        get: operations["getPreferences"];
        /** Create or update a single preference */
        put: operations["upsertPreference"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tokens": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List API tokens owned by the caller */
        get: operations["listAPITokens"];
        put?: never;
        /**
         * Create a new API token
         * @description Mints a long-lived Bearer token scoped to the caller's account. The raw token
         *     value is returned exactly once in the response and never re-fetchable. API
         *     tokens cannot be used to mint other API tokens — this endpoint requires a JWT.
         */
        post: operations["createAPIToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tokens/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Revoke an API token
         * @description Marks the token as revoked. The row is preserved so the listing UI can show "Revoked on …".
         */
        delete: operations["revokeAPIToken"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/teams": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List teams for the authenticated user */
        get: operations["listTeams"];
        put?: never;
        /**
         * Create a new team
         * @description The authenticated user automatically becomes the team's first admin member.
         */
        post: operations["createTeam"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/teams/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a team by ID
         * @description Any member of the team may fetch the team record.
         */
        get: operations["getTeam"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Partially update a team (admin only)
         * @description Only fields present in the request body are modified. Only team admins may update.
         */
        patch: operations["updateTeam"];
        trace?: never;
    };
    "/teams/{id}/archive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Archive a team (admin only)
         * @description Sets archivedAt on the team. The team is hidden from active pickers but all data is preserved.
         */
        post: operations["archiveTeam"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/teams/{id}/unarchive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Restore a previously archived team (admin only) */
        post: operations["unarchiveTeam"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/teams/{id}/invites": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List pending invites for a team (admin only) */
        get: operations["listInvites"];
        put?: never;
        /**
         * Create a team invite
         * @description Only team admins may create invites. The token expires after 7 days.
         */
        post: operations["createInvite"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/teams/{id}/invites/{inviteId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Revoke a pending invite (admin only) */
        delete: operations["revokeInvite"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/teams/{id}/invite-link": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the current reusable invite link token (admin only) */
        get: operations["getInviteLink"];
        put?: never;
        /** Generate or regenerate the reusable invite link (admin only) */
        post: operations["createInviteLink"];
        /** Revoke the reusable invite link (admin only) */
        delete: operations["revokeInviteLink"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/teams/{id}/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List members of a team */
        get: operations["listTeamMembers"];
        put?: never;
        /** Add an existing registered user to a team (admin only) */
        post: operations["addMember"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/teams/{id}/members/{memberId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a team member with computed stats */
        get: operations["getMember"];
        put?: never;
        post?: never;
        /** Remove a member from a team (admin only) */
        delete: operations["deleteMember"];
        options?: never;
        head?: never;
        /** Update a team member's display name, identity, or role */
        patch: operations["updateMember"];
        trace?: never;
    };
    "/teams/{id}/members/{memberId}/archive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Inactivate a team member (admin only) */
        post: operations["archiveMember"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/teams/{id}/members/{memberId}/unarchive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reactivate an inactivated team member (admin only) */
        post: operations["unarchiveMember"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/teams/{id}/participants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a login-less participant (admin only) */
        post: operations["createParticipant"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search users by name or email
         * @description Returns up to 20 matching non-archived users. Query must be at least 2 characters.
         */
        get: operations["searchUsers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{id}/promote": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Grant superadmin status to a user (superadmin only) */
        post: operations["promoteUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{id}/archive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Inactivate a user account (superadmin only) */
        post: operations["archiveUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{id}/unarchive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reactivate an inactivated user account (superadmin only) */
        post: operations["unarchiveUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{id}/revoke": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Atomically revoke all access for a user (superadmin only)
         * @description Sets users.archived_at (blocks login everywhere), inactivates all team memberships that have activity assignments, and hard-deletes memberships with zero assignments. Returns a summary of the three operations.
         */
        post: operations["revokeUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Hard-delete a user (superadmin only)
         * @description Only permitted when the user has no active activities and belongs to a single team.
         */
        delete: operations["deleteUser"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/teams/{id}/activities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List activities for a team
         * @description Archived activities are excluded by default. Optional date-range filter on startAt.
         */
        get: operations["listActivities"];
        put?: never;
        /** Create an activity in a team */
        post: operations["createActivity"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/activities/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete an activity */
        delete: operations["deleteActivity"];
        options?: never;
        head?: never;
        /**
         * Partially update an activity
         * @description Only fields present in the request body are modified (true PATCH semantics).
         */
        patch: operations["updateActivity"];
        trace?: never;
    };
    "/activities/{id}/archive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Archive an activity (soft delete)
         * @description Sets archivedAt on the activity so it is hidden from default list responses but can be restored via /activities/{id}/unarchive.
         */
        post: operations["archiveActivity"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/activities/{id}/unarchive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Restore a previously archived activity */
        post: operations["unarchiveActivity"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/teams/{id}/timelines": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List timelines for a team */
        get: operations["listTimelines"];
        put?: never;
        /**
         * Create a timeline for a team
         * @description The authenticated user must be a member of the team. Restricted timelines automatically grant access to the creator.
         */
        post: operations["createTimeline"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/timelines/{id}/archive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Archive a timeline (admin only)
         * @description Team admins only. Sets archivedAt on the timeline so it is hidden from default list responses but can be restored via /timelines/{id}/unarchive.
         */
        post: operations["archiveTimeline"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/timelines/{id}/unarchive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Restore a previously archived timeline */
        post: operations["unarchiveTimeline"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/timelines/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Fetch a timeline by ID
         * @description Requires team membership. Restricted timelines additionally require an entry in the access list.
         */
        get: operations["getTimeline"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/teams/{id}/saved_filters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the authenticated user's saved filters for a team */
        get: operations["listSavedFilters"];
        put?: never;
        /** Create a saved filter for the authenticated user in a team */
        post: operations["createSavedFilter"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/saved_filters/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete a saved filter (owner only) */
        delete: operations["deleteSavedFilter"];
        options?: never;
        head?: never;
        /** Partially update a saved filter (owner only) */
        patch: operations["updateSavedFilter"];
        trace?: never;
    };
    "/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update the authenticated user's display name, color, and icon */
        patch: operations["updateProfile"];
        trace?: never;
    };
    "/users/me/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Change the authenticated user's password */
        put: operations["changePassword"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/forgot-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Request a password reset email */
        post: operations["forgotPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/reset-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reset a password using a valid reset token */
        post: operations["resetPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/smtp": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get current SMTP configuration (password masked) */
        get: operations["getSMTPConfig"];
        /** Save and validate SMTP configuration */
        put: operations["putSMTPConfig"];
        post?: never;
        /** Clear SMTP configuration */
        delete: operations["deleteSMTPConfig"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/smtp/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Send a test email using supplied config without saving */
        post: operations["testSMTPConfig"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get instance-level settings */
        get: operations["getAdminSettings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update one or more instance-level settings */
        patch: operations["patchAdminSettings"];
        trace?: never;
    };
    "/admin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all users with team membership counts */
        get: operations["listAdminUsers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/timelines/share/{token}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Fetch a timeline via its public share token
         * @description No authentication required. The share token itself is the credential.
         */
        get: operations["getTimelineByShareToken"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        User: {
            id: string;
            /** Format: email */
            email: string;
            displayName: string;
            avatarUrl?: string | null;
            /** @description User-level identity color ID. Propagates to team memberships. */
            color?: string | null;
            /** @description User-level identity icon ID. Propagates to team memberships. */
            icon?: string | null;
            isSuperadmin: boolean;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            /** Format: date-time */
            archivedAt?: string | null;
        };
        UpdateProfileInput: {
            displayName?: string;
            color?: string | null;
            icon?: string | null;
        };
        ChangePasswordInput: {
            currentPassword: string;
            newPassword: string;
        };
        ForgotPasswordInput: {
            /** Format: email */
            email: string;
        };
        ResetPasswordInput: {
            token: string;
            newPassword: string;
        };
        SMTPConfig: {
            host?: string;
            port?: number;
            username?: string;
            /** @description Masked in GET responses. */
            password?: string;
            fromName?: string;
            fromEmail?: string;
            /** @enum {string} */
            encryption?: "none" | "tls" | "starttls";
        };
        AdminUserRow: {
            teamCount?: number;
        } & components["schemas"]["User"];
        Team: {
            id: string;
            name: string;
            slug: string;
            description?: string | null;
            notes?: string | null;
            /** @description Identity color ID (e.g. "teal"). Null until explicitly set. */
            color?: string | null;
            /** @description Identity icon ID (e.g. "briefcase") or special value. Null until explicitly set. */
            icon?: string | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            /** Format: date-time */
            archivedAt?: string | null;
        };
        TeamMember: {
            /** @description Team-member record ID (team_members.id). */
            id: string;
            teamId: string;
            userId?: string | null;
            /** @enum {string} */
            role: "admin" | "member";
            /** @description Identity color ID (e.g. "teal"). Null until explicitly set. */
            color?: string | null;
            /** @description Identity icon ID or special value. Null until explicitly set. */
            icon?: string | null;
            /** Format: date-time */
            joinedAt: string;
            /**
             * Format: date-time
             * @description Non-null when the member is inactivated.
             */
            archivedAt?: string | null;
        };
        TeamMemberWithUser: components["schemas"]["TeamMember"] & {
            /** Format: email */
            email: string;
            displayName: string;
            avatarUrl?: string | null;
        };
        MemberStats: {
            activeTimelines: number;
            archivedTimelines: number;
            /** @description Activities with end_at in the past, not archived. */
            pastDue: number;
            /** @description Activities currently in progress (start_at ≤ now ≤ end_at), not archived. */
            running: number;
            /** @description Activities with start_at in the future, not archived. */
            upcoming: number;
            /** @description Activities with no start or end date, not archived. */
            unscheduled: number;
            archivedActivities: number;
        };
        MemberDetail: components["schemas"]["TeamMemberWithUser"] & {
            stats: components["schemas"]["MemberStats"];
            teams: components["schemas"]["TeamMemberWithUser"][];
            /** @description True when the member can be hard-deleted (no active activities, single team). */
            deletable: boolean;
            /**
             * Format: date-time
             * @description Set when the user account is deactivated (users.archived_at). Null for active accounts and participants.
             */
            userArchivedAt?: string | null;
        };
        Invite: {
            id: string;
            teamId: string;
            email: string;
            token: string;
            /** @enum {string} */
            role: "admin" | "member";
            invitedBy: string;
            /** Format: date-time */
            expiresAt: string;
            /** Format: date-time */
            acceptedAt?: string | null;
            /** Format: date-time */
            createdAt: string;
        };
        InviteLink: {
            /** @description The current invite link token, or null if none is set. */
            token: string | null;
        };
        Activity: {
            id: string;
            teamId: string;
            title: string;
            description?: string | null;
            icon?: string | null;
            color?: string | null;
            /** Format: date-time */
            startAt: string;
            /** Format: date-time */
            endAt: string;
            allDay: boolean;
            statusId?: string | null;
            parentActivityId?: string | null;
            percentComplete?: number | null;
            location?: string | null;
            url?: string | null;
            rrule?: string | null;
            /** @description External CalDAV VEVENT UID — preserved from Phase 12 calendar sync. */
            caldavUid?: string | null;
            /** @description External Google Calendar event ID — preserved from Phase 12 calendar sync. */
            googleEventId?: string | null;
            createdBy: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            /** Format: date-time */
            archivedAt?: string | null;
            /** @description IDs of team_members assigned to this activity (from activity_assignments). */
            assignedMemberIds?: string[];
        };
        Timeline: {
            id: string;
            teamId: string;
            name: string;
            /** @description Identity color ID (e.g. "teal"). Null until explicitly set. */
            color?: string | null;
            /** @description Identity icon ID or special value. Null until explicitly set. */
            icon?: string | null;
            /** Format: date */
            startDate: string;
            /** Format: date */
            endDate: string;
            shareToken: string;
            icalToken: string;
            createdBy: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            /** Format: date-time */
            archivedAt?: string | null;
        };
        SavedFilter: {
            id: string;
            teamId: string;
            userId: string;
            name: string;
            /** @description Opaque JSON filter spec (validated client-side). */
            definition: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        UserPreference: {
            id: string;
            userId: string;
            /** @description Empty string or absent means global (not timeline-scoped). */
            timelineId?: string | null;
            /** @description Preference key (e.g. group_by, sort_by, zoom_granularity, theme). */
            key: string;
            /** @description JSON-encoded preference value. */
            value: string;
            /** Format: date-time */
            updatedAt: string;
        };
        APIToken: {
            id: string;
            userId: string;
            /** @description Human-readable label (e.g. "ci-readonly"). */
            name: string;
            /** @enum {string} */
            scope: "read" | "add" | "edit_own" | "edit_all";
            /** Format: date-time */
            lastUsedAt?: string | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            revokedAt?: string | null;
        };
        APITokenCreated: components["schemas"]["APIToken"] & {
            /** @description The raw token value. Returned exactly once at creation; never re-fetchable. */
            token: string;
        };
        AuthResponse: {
            user: components["schemas"]["User"];
            accessToken: string;
            refreshToken: string;
        };
        RefreshResponse: {
            accessToken: string;
        };
        HealthResponse: {
            /** @enum {string} */
            status: "ok";
        };
        ApiError: {
            error: {
                code: string;
                message: string;
            };
        };
        RevokeUserResult: {
            accountDeactivated: boolean;
            membershipsInactivated: number;
            membershipsRemoved: number;
        };
    };
    responses: {
        /** @description Invalid request body or parameters. */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiError"];
            };
        };
        /** @description Missing or invalid authentication token. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiError"];
            };
        };
        /** @description Authenticated but not allowed to perform this action. */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiError"];
            };
        };
        /** @description Resource not found. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiError"];
            };
        };
        /** @description Tier limit reached. */
        PaymentRequired: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiError"];
            };
        };
        /** @description Unexpected server error. */
        InternalError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiError"];
            };
        };
    };
    parameters: {
        /** @description Team ID. */
        teamId: string;
        /** @description Activity ID. */
        activityId: string;
        /** @description Timeline ID. */
        timelineId: string;
        /** @description Saved filter ID. */
        savedFilterId: string;
        /** @description Public share token for a timeline. */
        shareToken: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Server is healthy. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: email */
                    email: string;
                    password: string;
                    displayName: string;
                    inviteToken?: string;
                };
            };
        };
        responses: {
            /** @description User registered successfully. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            402: components["responses"]["PaymentRequired"];
            403: components["responses"]["Forbidden"];
            /** @description Email address is already registered. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            500: components["responses"]["InternalError"];
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: email */
                    email: string;
                    password: string;
                };
            };
        };
        responses: {
            /** @description Authenticated successfully. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalError"];
        };
    };
    refreshToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    refreshToken: string;
                };
            };
        };
        responses: {
            /** @description New access token issued. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RefreshResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalError"];
        };
    };
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current user profile. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalError"];
        };
    };
    getPreferences: {
        parameters: {
            query?: {
                /** @description Scope results to a specific timeline. Omit for global prefs. */
                timeline_id?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Array of matching preferences. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserPreference"][];
                };
            };
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalError"];
        };
    };
    upsertPreference: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description Preference key (e.g. group_by, sort_by, zoom_granularity, theme). */
                    key: string;
                    /** @description JSON-encoded preference value. */
                    value: string;
                    /** @description Omit or pass "" for a global preference. */
                    timelineId?: string | null;
                };
            };
        };
        responses: {
            /** @description Upserted preference. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserPreference"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalError"];
        };
    };
    listAPITokens: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Array of tokens (active and revoked). Raw token value is never included. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIToken"][];
                };
            };
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalError"];
        };
    };
    createAPIToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name: string;
                    /** @enum {string} */
                    scope: "read" | "add" | "edit_own" | "edit_all";
                };
            };
        };
        responses: {
            /** @description Token created. The raw value is included in this response only. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APITokenCreated"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            500: components["responses"]["InternalError"];
        };
    };
    revokeAPIToken: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Token revoked (or already revoked). */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    listTeams: {
        parameters: {
            query?: {
                /** @description When `true`, include archived teams. Default excludes them. */
                archived?: "true" | "false";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Array of teams the user belongs to. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Team"][];
                };
            };
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalError"];
        };
    };
    createTeam: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name: string;
                    description?: string | null;
                    notes?: string | null;
                    color?: string | null;
                    icon?: string | null;
                };
            };
        };
        responses: {
            /** @description Team created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Team"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            402: components["responses"]["PaymentRequired"];
            500: components["responses"]["InternalError"];
        };
    };
    getTeam: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Team ID. */
                id: components["parameters"]["teamId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Team record. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Team"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    updateTeam: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Team ID. */
                id: components["parameters"]["teamId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name?: string;
                    description?: string | null;
                    notes?: string | null;
                    color?: string | null;
                    icon?: string | null;
                };
            };
        };
        responses: {
            /** @description Updated team. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Team"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    archiveTeam: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Team ID. */
                id: components["parameters"]["teamId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The archived team. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Team"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    unarchiveTeam: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Team ID. */
                id: components["parameters"]["teamId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The restored team. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Team"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    listInvites: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Team ID. */
                id: components["parameters"]["teamId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Array of pending invites. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Invite"][];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            500: components["responses"]["InternalError"];
        };
    };
    createInvite: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Team ID. */
                id: components["parameters"]["teamId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /**
                     * Format: email
                     * @description If provided, the invite is scoped to this email address.
                     */
                    email?: string;
                    /**
                     * @default member
                     * @enum {string}
                     */
                    role?: "admin" | "member";
                };
            };
        };
        responses: {
            /** @description Invite created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Invite"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            500: components["responses"]["InternalError"];
        };
    };
    revokeInvite: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Team ID. */
                id: components["parameters"]["teamId"];
                inviteId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Invite revoked. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            500: components["responses"]["InternalError"];
        };
    };
    getInviteLink: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Team ID. */
                id: components["parameters"]["teamId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current invite link token (null if none is set). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InviteLink"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            500: components["responses"]["InternalError"];
        };
    };
    createInviteLink: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Team ID. */
                id: components["parameters"]["teamId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description New invite link token. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InviteLink"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            500: components["responses"]["InternalError"];
        };
    };
    revokeInviteLink: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Team ID. */
                id: components["parameters"]["teamId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Invite link revoked. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            500: components["responses"]["InternalError"];
        };
    };
    listTeamMembers: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Team ID. */
                id: components["parameters"]["teamId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Array of team members with user display info. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamMemberWithUser"][];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            500: components["responses"]["InternalError"];
        };
    };
    addMember: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Team ID. */
                id: components["parameters"]["teamId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    userId: string;
                    /**
                     * @default member
                     * @enum {string}
                     */
                    role?: "admin" | "member";
                };
            };
        };
        responses: {
            /** @description Member added. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamMemberWithUser"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            /** @description User is already a member. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            500: components["responses"]["InternalError"];
        };
    };
    getMember: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Team ID. */
                id: components["parameters"]["teamId"];
                memberId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Member detail with stats. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemberDetail"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    deleteMember: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Team ID. */
                id: components["parameters"]["teamId"];
                memberId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Member removed. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            /** @description Cannot remove the last admin. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            500: components["responses"]["InternalError"];
        };
    };
    updateMember: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Team ID. */
                id: components["parameters"]["teamId"];
                memberId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    displayName?: string | null;
                    color?: string | null;
                    icon?: string | null;
                    /** @enum {string} */
                    role?: "admin" | "member";
                };
            };
        };
        responses: {
            /** @description Updated member. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamMemberWithUser"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            /** @description Cannot demote the last admin. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            500: components["responses"]["InternalError"];
        };
    };
    archiveMember: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Team ID. */
                id: components["parameters"]["teamId"];
                memberId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Inactivated member. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamMemberWithUser"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            /** @description Cannot inactivate the last admin. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            500: components["responses"]["InternalError"];
        };
    };
    unarchiveMember: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Team ID. */
                id: components["parameters"]["teamId"];
                memberId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Reactivated member. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamMemberWithUser"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    createParticipant: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Team ID. */
                id: components["parameters"]["teamId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name: string;
                    color?: string | null;
                    icon?: string | null;
                };
            };
        };
        responses: {
            /** @description Participant created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamMemberWithUser"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            500: components["responses"]["InternalError"];
        };
    };
    searchUsers: {
        parameters: {
            query: {
                q: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Matching users. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"][];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalError"];
        };
    };
    promoteUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Updated user. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    archiveUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Inactivated user. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    unarchiveUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Reactivated user. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    revokeUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Revocation summary. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RevokeUserResult"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    deleteUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User deleted. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            /** @description User cannot be deleted (multi-team or has active activities). */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            500: components["responses"]["InternalError"];
        };
    };
    listActivities: {
        parameters: {
            query?: {
                /** @description Only return activities where startAt >= from (RFC 3339). */
                from?: string;
                /** @description Only return activities where startAt <= to (RFC 3339). */
                to?: string;
                /** @description When `true`, include archived activities. Default excludes them. */
                archived?: "true" | "false";
            };
            header?: never;
            path: {
                /** @description Team ID. */
                id: components["parameters"]["teamId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Array of activities. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Activity"][];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            500: components["responses"]["InternalError"];
        };
    };
    createActivity: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Team ID. */
                id: components["parameters"]["teamId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    title: string;
                    description?: string | null;
                    icon?: string | null;
                    color?: string | null;
                    /** Format: date-time */
                    startAt: string;
                    /** Format: date-time */
                    endAt: string;
                    /** @default false */
                    allDay?: boolean;
                    statusId?: string | null;
                    parentActivityId?: string | null;
                    percentComplete?: number | null;
                    location?: string | null;
                    url?: string | null;
                    rrule?: string | null;
                    /** @description IDs of team_members to assign. Replaces all existing assignments. */
                    assignedMemberIds?: string[];
                };
            };
        };
        responses: {
            /** @description Activity created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Activity"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            500: components["responses"]["InternalError"];
        };
    };
    deleteActivity: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Activity ID. */
                id: components["parameters"]["activityId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Activity deleted (no body). */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    updateActivity: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Activity ID. */
                id: components["parameters"]["activityId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    title?: string;
                    description?: string | null;
                    icon?: string | null;
                    color?: string | null;
                    /** Format: date-time */
                    startAt?: string;
                    /** Format: date-time */
                    endAt?: string;
                    allDay?: boolean;
                    statusId?: string | null;
                    parentActivityId?: string | null;
                    percentComplete?: number | null;
                    location?: string | null;
                    url?: string | null;
                    rrule?: string | null;
                    /** @description IDs of team_members to assign. Replaces all existing assignments. */
                    assignedMemberIds?: string[];
                };
            };
        };
        responses: {
            /** @description Updated activity. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Activity"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    archiveActivity: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Activity ID. */
                id: components["parameters"]["activityId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The archived activity. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Activity"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    unarchiveActivity: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Activity ID. */
                id: components["parameters"]["activityId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The restored activity. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Activity"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    listTimelines: {
        parameters: {
            query?: {
                /** @description When `true`, include archived timelines. Default excludes them. */
                archived?: "true" | "false";
            };
            header?: never;
            path: {
                /** @description Team ID. */
                id: components["parameters"]["teamId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Array of non-archived timelines for the team. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Timeline"][];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            500: components["responses"]["InternalError"];
        };
    };
    createTimeline: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Team ID. */
                id: components["parameters"]["teamId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name: string;
                    /** Format: date */
                    startDate: string;
                    /** Format: date */
                    endDate: string;
                };
            };
        };
        responses: {
            /** @description Timeline created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Timeline"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            500: components["responses"]["InternalError"];
        };
    };
    archiveTimeline: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Timeline ID. */
                id: components["parameters"]["timelineId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The archived timeline. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Timeline"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    unarchiveTimeline: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Timeline ID. */
                id: components["parameters"]["timelineId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The restored timeline. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Timeline"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    getTimeline: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Timeline ID. */
                id: components["parameters"]["timelineId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Timeline found. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Timeline"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    listSavedFilters: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Team ID. */
                id: components["parameters"]["teamId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Array of saved filters owned by the caller. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SavedFilter"][];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            500: components["responses"]["InternalError"];
        };
    };
    createSavedFilter: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Team ID. */
                id: components["parameters"]["teamId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name: string;
                    /** @description Opaque JSON filter spec (validated client-side). */
                    definition: string;
                };
            };
        };
        responses: {
            /** @description Saved filter created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SavedFilter"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            500: components["responses"]["InternalError"];
        };
    };
    deleteSavedFilter: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Saved filter ID. */
                id: components["parameters"]["savedFilterId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Saved filter deleted (no body). */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    updateSavedFilter: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Saved filter ID. */
                id: components["parameters"]["savedFilterId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name?: string;
                    definition?: string;
                };
            };
        };
        responses: {
            /** @description Updated saved filter. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SavedFilter"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    updateProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateProfileInput"];
            };
        };
        responses: {
            /** @description Updated user profile. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalError"];
        };
    };
    changePassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangePasswordInput"];
            };
        };
        responses: {
            /** @description Password changed successfully. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalError"];
        };
    };
    forgotPassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ForgotPasswordInput"];
            };
        };
        responses: {
            /** @description Always 200; no email enumeration. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
        };
    };
    resetPassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResetPasswordInput"];
            };
        };
        responses: {
            /** @description Password reset successfully. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            500: components["responses"]["InternalError"];
        };
    };
    getSMTPConfig: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description SMTP config or null when not configured. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    putSMTPConfig: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SMTPConfig"];
            };
        };
        responses: {
            /** @description SMTP config saved. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    deleteSMTPConfig: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description SMTP config cleared. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    testSMTPConfig: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SMTPConfig"];
            };
        };
        responses: {
            /** @description Test email sent. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    getAdminSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Instance settings map. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    patchAdminSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: string;
                };
            };
        };
        responses: {
            /** @description Updated settings. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    listAdminUsers: {
        parameters: {
            query?: {
                /** @description When true, return only users with zero active team memberships. */
                orphaned?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of admin user rows. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        users?: components["schemas"]["AdminUserRow"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    getTimelineByShareToken: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Public share token for a timeline. */
                token: components["parameters"]["shareToken"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Timeline found. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Timeline"];
                };
            };
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
}
