/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health check */
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register a new user
         * @description The first user on a fresh install may register without an invite token
         *     (bootstrap). Every subsequent user must supply a valid invite token.
         */
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Authenticate and obtain tokens */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Exchange a refresh token for a new access token */
        post: operations["refreshToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the authenticated user's profile */
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/teams": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List teams for the authenticated user */
        get: operations["listTeams"];
        put?: never;
        /**
         * Create a new team
         * @description The authenticated user automatically becomes the team's first admin member.
         */
        post: operations["createTeam"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/teams/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a team by ID
         * @description Any member of the team may fetch the team record.
         */
        get: operations["getTeam"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/teams/{id}/invites": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create a team invite
         * @description Only team admins may create invites. The token expires after 7 days.
         */
        post: operations["createInvite"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/teams/{id}/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List members of a team */
        get: operations["listTeamMembers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/teams/{id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List events for a team
         * @description Archived events are excluded by default. Optional date-range filter on startAt.
         */
        get: operations["listEvents"];
        put?: never;
        /** Create an event in a team */
        post: operations["createEvent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete an event */
        delete: operations["deleteEvent"];
        options?: never;
        head?: never;
        /**
         * Partially update an event
         * @description Only fields present in the request body are modified (true PATCH semantics).
         */
        patch: operations["updateEvent"];
        trace?: never;
    };
    "/teams/{id}/timelines": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List timelines for a team */
        get: operations["listTimelines"];
        put?: never;
        /**
         * Create a timeline for a team
         * @description The authenticated user must be a member of the team. Restricted timelines automatically grant access to the creator.
         */
        post: operations["createTimeline"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/timelines/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Fetch a timeline by ID
         * @description Requires team membership. Restricted timelines additionally require an entry in the access list.
         */
        get: operations["getTimeline"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/teams/{id}/saved_filters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the authenticated user's saved filters for a team */
        get: operations["listSavedFilters"];
        put?: never;
        /** Create a saved filter for the authenticated user in a team */
        post: operations["createSavedFilter"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/saved_filters/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete a saved filter (owner only) */
        delete: operations["deleteSavedFilter"];
        options?: never;
        head?: never;
        /** Partially update a saved filter (owner only) */
        patch: operations["updateSavedFilter"];
        trace?: never;
    };
    "/timelines/share/{token}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Fetch a timeline via its public share token
         * @description No authentication required. The share token itself is the credential.
         */
        get: operations["getTimelineByShareToken"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        User: {
            id: string;
            /** Format: email */
            email: string;
            displayName: string;
            avatarUrl?: string | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        Team: {
            id: string;
            name: string;
            slug: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        TeamMember: {
            /** @description Team-member record ID (team_members.id). */
            id: string;
            teamId: string;
            userId?: string | null;
            /** @enum {string} */
            role: "owner" | "admin" | "member";
            color?: string | null;
            /** Format: date-time */
            joinedAt: string;
        };
        TeamMemberWithUser: components["schemas"]["TeamMember"] & {
            /** Format: email */
            email: string;
            displayName: string;
            avatarUrl?: string | null;
        };
        Invite: {
            id: string;
            teamId: string;
            email: string;
            token: string;
            /** @enum {string} */
            role: "admin" | "member";
            invitedBy: string;
            /** Format: date-time */
            expiresAt: string;
            /** Format: date-time */
            acceptedAt?: string | null;
            /** Format: date-time */
            createdAt: string;
        };
        Event: {
            id: string;
            teamId: string;
            title: string;
            description?: string | null;
            icon?: string | null;
            color?: string | null;
            /** Format: date-time */
            startAt: string;
            /** Format: date-time */
            endAt: string;
            allDay: boolean;
            statusId?: string | null;
            parentEventId?: string | null;
            percentComplete?: number | null;
            location?: string | null;
            url?: string | null;
            rrule?: string | null;
            caldavUid?: string | null;
            googleEventId?: string | null;
            createdBy: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            /** Format: date-time */
            archivedAt?: string | null;
            /** @description IDs of team_members assigned to this event (from event_assignments). */
            assignedMemberIds?: string[];
        };
        Timeline: {
            id: string;
            teamId: string;
            name: string;
            /** Format: date */
            startDate: string;
            /** Format: date */
            endDate: string;
            /** @enum {string} */
            visibility: "public" | "restricted";
            shareToken: string;
            icalToken: string;
            createdBy: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            /** Format: date-time */
            archivedAt?: string | null;
        };
        SavedFilter: {
            id: string;
            teamId: string;
            userId: string;
            name: string;
            /** @description Opaque JSON filter spec (validated client-side). */
            definition: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        AuthResponse: {
            user: components["schemas"]["User"];
            accessToken: string;
            refreshToken: string;
        };
        RefreshResponse: {
            accessToken: string;
        };
        HealthResponse: {
            /** @enum {string} */
            status: "ok";
        };
        ApiError: {
            error: {
                code: string;
                message: string;
            };
        };
    };
    responses: {
        /** @description Invalid request body or parameters. */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiError"];
            };
        };
        /** @description Missing or invalid authentication token. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiError"];
            };
        };
        /** @description Authenticated but not allowed to perform this action. */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiError"];
            };
        };
        /** @description Resource not found. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiError"];
            };
        };
        /** @description Tier limit reached. */
        PaymentRequired: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiError"];
            };
        };
        /** @description Unexpected server error. */
        InternalError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiError"];
            };
        };
    };
    parameters: {
        /** @description Team ID. */
        teamId: string;
        /** @description Event ID. */
        eventId: string;
        /** @description Timeline ID. */
        timelineId: string;
        /** @description Saved filter ID. */
        savedFilterId: string;
        /** @description Public share token for a timeline. */
        shareToken: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Server is healthy. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: email */
                    email: string;
                    password: string;
                    displayName: string;
                    inviteToken?: string;
                };
            };
        };
        responses: {
            /** @description User registered successfully. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            402: components["responses"]["PaymentRequired"];
            403: components["responses"]["Forbidden"];
            /** @description Email address is already registered. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            500: components["responses"]["InternalError"];
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: email */
                    email: string;
                    password: string;
                };
            };
        };
        responses: {
            /** @description Authenticated successfully. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalError"];
        };
    };
    refreshToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    refreshToken: string;
                };
            };
        };
        responses: {
            /** @description New access token issued. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RefreshResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalError"];
        };
    };
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current user profile. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalError"];
        };
    };
    listTeams: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Array of teams the user belongs to. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Team"][];
                };
            };
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalError"];
        };
    };
    createTeam: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name: string;
                };
            };
        };
        responses: {
            /** @description Team created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Team"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            402: components["responses"]["PaymentRequired"];
            500: components["responses"]["InternalError"];
        };
    };
    getTeam: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Team ID. */
                id: components["parameters"]["teamId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Team record. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Team"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    createInvite: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Team ID. */
                id: components["parameters"]["teamId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /**
                     * Format: email
                     * @description If provided, the invite is scoped to this email address.
                     */
                    email?: string;
                    /**
                     * @default member
                     * @enum {string}
                     */
                    role?: "admin" | "member";
                };
            };
        };
        responses: {
            /** @description Invite created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Invite"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            500: components["responses"]["InternalError"];
        };
    };
    listTeamMembers: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Team ID. */
                id: components["parameters"]["teamId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Array of team members with user display info. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamMemberWithUser"][];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            500: components["responses"]["InternalError"];
        };
    };
    listEvents: {
        parameters: {
            query?: {
                /** @description Only return events where startAt >= from (RFC 3339). */
                from?: string;
                /** @description Only return events where startAt <= to (RFC 3339). */
                to?: string;
            };
            header?: never;
            path: {
                /** @description Team ID. */
                id: components["parameters"]["teamId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Array of events. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Event"][];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            500: components["responses"]["InternalError"];
        };
    };
    createEvent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Team ID. */
                id: components["parameters"]["teamId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    title: string;
                    description?: string | null;
                    icon?: string | null;
                    color?: string | null;
                    /** Format: date-time */
                    startAt: string;
                    /** Format: date-time */
                    endAt: string;
                    /** @default false */
                    allDay?: boolean;
                    statusId?: string | null;
                    parentEventId?: string | null;
                    percentComplete?: number | null;
                    location?: string | null;
                    url?: string | null;
                    rrule?: string | null;
                };
            };
        };
        responses: {
            /** @description Event created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Event"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            500: components["responses"]["InternalError"];
        };
    };
    deleteEvent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Event ID. */
                id: components["parameters"]["eventId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Event deleted (no body). */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    updateEvent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Event ID. */
                id: components["parameters"]["eventId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    title?: string;
                    description?: string | null;
                    icon?: string | null;
                    color?: string | null;
                    /** Format: date-time */
                    startAt?: string;
                    /** Format: date-time */
                    endAt?: string;
                    allDay?: boolean;
                    statusId?: string | null;
                    parentEventId?: string | null;
                    percentComplete?: number | null;
                    location?: string | null;
                    url?: string | null;
                    rrule?: string | null;
                };
            };
        };
        responses: {
            /** @description Updated event. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Event"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    listTimelines: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Team ID. */
                id: components["parameters"]["teamId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Array of non-archived timelines for the team. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Timeline"][];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            500: components["responses"]["InternalError"];
        };
    };
    createTimeline: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Team ID. */
                id: components["parameters"]["teamId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name: string;
                    /** Format: date */
                    startDate: string;
                    /** Format: date */
                    endDate: string;
                    /**
                     * @default public
                     * @enum {string}
                     */
                    visibility?: "public" | "restricted";
                };
            };
        };
        responses: {
            /** @description Timeline created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Timeline"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            500: components["responses"]["InternalError"];
        };
    };
    getTimeline: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Timeline ID. */
                id: components["parameters"]["timelineId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Timeline found. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Timeline"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    listSavedFilters: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Team ID. */
                id: components["parameters"]["teamId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Array of saved filters owned by the caller. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SavedFilter"][];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            500: components["responses"]["InternalError"];
        };
    };
    createSavedFilter: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Team ID. */
                id: components["parameters"]["teamId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name: string;
                    /** @description Opaque JSON filter spec (validated client-side). */
                    definition: string;
                };
            };
        };
        responses: {
            /** @description Saved filter created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SavedFilter"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            500: components["responses"]["InternalError"];
        };
    };
    deleteSavedFilter: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Saved filter ID. */
                id: components["parameters"]["savedFilterId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Saved filter deleted (no body). */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    updateSavedFilter: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Saved filter ID. */
                id: components["parameters"]["savedFilterId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name?: string;
                    definition?: string;
                };
            };
        };
        responses: {
            /** @description Updated saved filter. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SavedFilter"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    getTimelineByShareToken: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Public share token for a timeline. */
                token: components["parameters"]["shareToken"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Timeline found. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Timeline"];
                };
            };
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
}
